# Generated by Django 4.2.5 on 2023-09-30 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hospital_patient", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppointmentDepartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="None", max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="appointmentmodel",
            name="Department",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="hospital_patient.appointmentdepartment",
            ),
            preserve_default=False,
        ),
    ]
