# Generated by Django 4.2.5 on 2023-09-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital_patient", "0002_appointmentdepartment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointmentmodel",
            name="Patient_Name",
            field=models.CharField(max_length=30),
        ),
    ]
