# Generated by Django 4.2.5 on 2023-10-01 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hospital_patient", "0003_alter_appointmentmodel_patient_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appointmentmodel",
            options={"ordering": ["-Date", "-Time"]},
        ),
    ]
