# Generated by Django 4.2.5 on 2023-10-03 11:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="description",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
