# Generated by Django 4.2.5 on 2023-10-04 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0006_categorie_delaidepaiement_devise_pays_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="compte",
            name="pays",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="crm.pays",
            ),
        ),
    ]
