# Generated by Django 4.2.5 on 2023-10-05 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0007_compte_pays"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compte",
            name="type",
            field=models.CharField(
                choices=[
                    ("Professionnel", "Professionnel"),
                    ("Fournisseur", "Fournisseur"),
                    ("Partenaire", "Partenaire"),
                ],
                max_length=20,
            ),
        ),
    ]
