# Generated by Django 4.2.5 on 2023-10-05 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0008_alter_compte_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="client",
            field=models.ForeignKey(
                default=124, on_delete=django.db.models.deletion.CASCADE, to="crm.compte"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="name",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
