# Generated by Django 4.2.5 on 2023-10-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0009_project_client_project_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
