# Generated by Django 4.2.5 on 2023-10-05 13:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0012_alter_project_end_date_alter_project_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="description",
            field=ckeditor.fields.RichTextField(default="This is the default text."),
        ),
        migrations.AlterField(
            model_name="project",
            name="title",
            field=models.CharField(
                default="This is the default project name.", max_length=200
            ),
        ),
    ]
