# Generated by Django 4.2.5 on 2023-10-05 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0014_invoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="compte",
            field=models.ForeignKey(
                default=173,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="crm.compte",
            ),
            preserve_default=False,
        ),
    ]
