# Generated by Django 4.2.5 on 2023-09-29 12:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("account", "0003_alter_profile_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="customgroup",
            name="members",
            field=models.ManyToManyField(
                blank=True, related_name="custom_groups", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
