# Generated by Django 4.2.5 on 2023-09-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_customgroup_members"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name="CustomGroup",
        ),
    ]
