# Generated by Django 4.2.5 on 2023-09-30 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_department_delete_customgroup"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="department",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.department",
            ),
            preserve_default=False,
        ),
    ]
