# Generated by Django 4.2.5 on 2023-09-30 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0007_alter_profile_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(default="None", max_length=100),
        ),
    ]
