# Generated by Django 4.2.5 on 2023-09-30 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0008_alter_department_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="department",
            field=models.ForeignKey(
                default=4,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.department",
            ),
        ),
    ]
