# Generated by Django 4.2.5 on 2023-09-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0010_profile_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="location",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
