# Generated by Django 4.2.5 on 2023-10-01 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0011_alter_profile_location"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name_plural": "Profiles"},
        ),
        migrations.RemoveField(
            model_name="profile",
            name="email",
        ),
    ]
